sudo: true
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -y --purge remove qt4-qmake
addons:
  apt:
    packages:
    - expat
    - fop
    - valgrind
    - xsltproc
    - libxml2-utils
    - qt5-default
    - qtbase5-dev
    - libqt5webkit5-dev
    - qttools5-dev-tools
script:
 - ./build_and_test
# TODO: build mac
