sudo: true
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - expat
    - fop
    - valgrind
    - xsltproc
    - libxml2-utils
    - qt5-qmake
script:
 - ./build_and_test
# TODO: build mac
