sudo: required
dist: trusty
services: docker
language: cpp
addons:
  apt:
    sources: &add-sources
    - sourceline: 'ppa:beineri/opt-qt595-trusty'
    packages: &trusty-packages
    - expat
    - fop
    - valgrind
    - xsltproc
    - libxml2-utils
    - libusb-dev
    - docbook-xml
    - docbook-xsl
matrix:
  include:
  - compiler: gcc
    env:
    - USE_DOCKER=false
    - QTDIR=/opt/qt59
    addons:
      apt:
        sources: *add-sources
        packages:
        - *trusty-packages
        - qt59base
        - qt59webengine
        - qt59translations
        - qt59tools
  - compiler: gcc
    env:
    - USE_DOCKER=true
    addons:
      apt:
        sources:
        packages:
  - compiler: clang
    env:
    - USE_DOCKER=true
    addons:
      apt:
        sources:
        packages:

install:
  - if [ "${USE_DOCKER}" = "false" ]; then wget 'https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage'; fi
  - if [ "${USE_DOCKER}" = "false" ]; then chmod +x linuxdeployqt-continuous-x86_64.AppImage; fi
  - if [ "${USE_DOCKER}" = "false" ]; then mv linuxdeployqt-continuous-x86_64.AppImage linuxdeployqt; fi

script:
  - if [ "${USE_DOCKER}" = "true" ]; then ./docker_hook; fi
  - if [ "${USE_DOCKER}" = "false" ]; then QMAKE=${QTDIR}/bin/qmake LUPDATE=${QTDIR}/bin/lupdate LRELEASE=${QTDIR}/bin/lrelease LDFLAGS="-Wl,-rpath,${QTDIR}/lib -L${QTDIR}/lib" ./build_and_test; fi
  - if [ "${USE_DOCKER}" = "false" ]; then export VERSION=$(git rev-parse --short HEAD); fi # linuxdeployqt uses this for naming the file
  - if [ "${USE_DOCKER}" = "false" ]; then cd gui; QMAKE=${QTDIR}/bin/qmake LINUXDEPLOYQT=../linuxdeployqt ./makeappimage.sh; fi

after_success:
  - pwd
  - ls -l *AppImage*
  - if [ "${USE_DOCKER}" = "false" ]; then wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh; fi
  - if [ "${USE_DOCKER}" = "false" ]; then bash ./upload.sh  GPSBabelFE-*.AppImage*; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
