sudo: true
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind expat
addons:
  apt:
    packages:
    - expat
    - fop
    - valgrind
    - xsltproc
script:
 - ./build_and_test
# TODO: build mac
