language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      cache:
        directories:
          - $HOME/Qt
        timeout: 600
    - os: osx
      compiler: clang
      cache:
        directories:
          - $HOME/Cache
        timeout: 600

script:
  - ./tools/lookup

