# this file is used to build the image gpsbabel_build_environment used by travis.

FROM ubuntu:bionic as qt_install
WORKDIR /app

# update environment.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

# install packages needed to install Qt
RUN apt-get update && apt-get install -y --no-install-recommends \
  libdbus-1-3 \
  libfreetype6 \
  libfontconfig1 \
  libx11-6 \
  libx11-xcb1 \
  ca-cacert \
  wget \
 && rm -rf /var/lib/apt/lists/*

# basic build and test tools
COPY ./qtci/install-qt ./qtci/extract-qt-installer /app/
RUN QT_CI_PACKAGES=qt.qt5.5121.gcc_64,qt.qt5.5121.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=/app:${PATH} ./install-qt 5.12.1 /opt

FROM ubuntu:bionic
LABEL maintainer="https://github.com/tsteven4"
WORKDIR /app

# update environment.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

# install packages needed for gpsbabel build
# split into multiple commands to limit layer size

# basic build and test tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    make \
    autoconf \
    gperf \
    git \
    valgrind \
    expat \
    libxml2-utils \
 && rm -rf /var/lib/apt/lists/*

# alternative compiler
RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
 && rm -rf /var/lib/apt/lists/*

# pkgs needed to build document
RUN apt-get update && apt-get install -y --no-install-recommends \
    fop \
    xsltproc \
    docbook-xml \
    docbook-xsl \
 && rm -rf /var/lib/apt/lists/*

# pkgs with libraries needed by gpsbabel
RUN apt-get update && apt-get install -y --no-install-recommends \
    libusb-dev \
 && rm -rf /var/lib/apt/lists/*

# dependencies of Qt
# some of these can be found by chasing dependencies of plugins
# shown by running the gui with export QT_DEBUG_PLUGINS=1.
# some were recommended by Qt.
# some showed up in messages to the terminal when running the gui.
RUN apt-get update && apt-get install -y --no-install-recommends \
    libasound2 \
    libatk1.0-0 \
    libcairo2 \
    libcairo-gobject2 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libglu1-mesa-dev \
    libgtk-3-0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libwayland-cursor0 \
    libwayland-egl1-mesa \
    libx11-xcb-dev \
    libxcomposite1 \
    libxcursor1 \
    libxkbcommon-x11-0 \
 && rm -rf /var/lib/apt/lists/*

# Qt
COPY --from=qt_install /opt/qt-5.12.1.env /opt/qtio.env
COPY --from=qt_install /opt/Qt/5.12.1 /opt/Qt/5.12.1
COPY --from=qt_install /opt/Qt/Licenses /opt/Qt/Licenses

# pkgs needed to generate coverage report:
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcovr \
    openjdk-8-jre-headless \
 && rm -rf /var/lib/apt/lists/*

# install environment for locale test
RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
 && rm -rf /var/lib/apt/lists/* \
 && locale-gen en_US \
 && locale-gen en_US.UTF-8 \
 && locale -a

