#!/bin/bash -ex
#
# This script is run on travis for the install stage of mac builds.
# Note the script must be sourced if you want the modified PATH to
# be used outside this script.
#

QT_VERSION=${1:-5.12.0}
QT_VERSION_SHORT=$(echo ${QT_VERSION} | sed 's/\.//g')

# our expectation is that install-qt-osx creates $QTDIR, $QTDIR/bin.
QTDIR=${HOME}/Qt/${QT_VERSION}/clang_64

if [ -d "${QTDIR}/bin" ]; then
  echo "Using cached Qt."
  echo "If you need to clear the cache see"
  echo "https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches."
else
  pushd ${HOME};
  rm -fr Qt
  # install-qt-osx creates the install at $PWD/Qt.
  QT_CI_PACKAGES=qt.${QT_VERSION_SHORT}.clang_64,qt.${QT_VERSION_SHORT}.qtwebengine PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt-osx ${QT_VERSION}
  popd;
fi
# note that qt-x.y.z.env created by install-qt-osx is not cached!
export PATH=${QTDIR}/bin:${PATH}
unset -v QTDIR
