#!/bin/bash -ex
#
# this script is run on travis for the script stage of mac builds
#

QMAKE=${QMAKE:-qmake}
LUPDATE=${LUPDATE:-lupdate}
LRELEASE=${LRELEASE:-lrelease}
MACDEPLOYQT=${MACDEPLOYQT:-macdeployqt}
# we assume we are on macOS, so date is not gnu date.
VERSIONID=${VERSIONID:-$(date -ju -f %Y-%m-%dT%H:%M:%S%z $(git show -s --format="%aI" HEAD | sed 's/:\(..\)$/\1/') +%Y%m%dT%H%MZ)-$(git rev-parse --short=7 HEAD)}

# debug tokens
"$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"/ci_tokens

# build and test the CLI
touch configure
touch xcsv_tokens.gperf
touch internal_styles.cc
./configure
make
cat Makefile.d
touch xcsv.h
make


