#!/bin/bash -ex
#
# This script is run on travis for the install stage of mac builds.
#

#debug failed install
function debug() {
  cat ${CACHEDIR}/qt-${QT_VERSION}.env
  find ${CACHEDIR}/Qt -maxdepth 3 -ls
  cat ${CACHEDIR}/Qt/InstallationLog.txt
  cat ${CACHEDIR}/Qt/components.xml
  echo "$1" >&2
  exit 1
}

# validate install
function validate() {
  (
    set +e
    source ${CACHEDIR}/qt-${QT_VERSION}.env
    if [ "$(qmake -query QT_INSTALL_BINS)" != "${QTDIR}/bin" ]; then
      debug "ERROR: unexpected Qt location."
    fi
    if [ "$(qmake -query QT_VERSION)" != "${QT_VERSION}" ]; then
      debug "ERROR: wrong Qt version."
    fi
  )
}

QT_VERSION=${1}

packages=( \
    expat \
    fop \
    valgrind \
    xsltproc \
    libxml2-utils \
    libusb-1.0-0-dev \
    docbook-xml \
    docbook-xsl \
    locales \
  )
# clazy first appeared in focal
if apt-cache show clazy 1>/dev/null 2>&1; then
  packages=( "${packages[@]}" \
      clazy \
    )
fi
if [ -z "${QT_VERSION}" ]; then
  packages=( "${packages[@]}" \
      qt5-default \
      qttools5-dev-tools \
      qttranslations5-l10n \
      qtwebengine5-dev  \
    )
fi
sudo apt-get update
sudo apt-get -y install "${packages[@]}"
# prepare locale for test_encoding_latin1, requires locales package.
sudo locale-gen en_US

if [ -n "${QT_VERSION}" ]; then
  QT_VERSION_SHORT=${QT_VERSION//./}

  # our expectation is that install-qt creates $QTDIR, $QTDIR/bin.
  CACHEDIR=${HOME}/Cache
  QTDIR=${CACHEDIR}/Qt/${QT_VERSION}/gcc_64

  if [ -d "${QTDIR}/bin" ]; then
    echo "Using cached Qt."
    echo "If you need to clear the cache see"
    echo "https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches."
    if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
      # the cache is being used.  modify it to reset expiration date.
      date > ${CACHEDIR}/timestamp
    fi
    if [ -f "${CACHEDIR}/timestamp" ]; then
      echo -n "Cache timestamp: "
      cat "${CACHEDIR}/timestamp"
    fi
  else
    rm -fr ${CACHEDIR}
    mkdir -p ${CACHEDIR}
    pushd ${CACHEDIR}
    # install-qt creates the install at $PWD/Qt.
    QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.gcc_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
    popd
    validate
    rm ${CACHEDIR}/qt-opensource*.run
  fi
fi
