name: gpsbabel # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: "Convert, manipulate and transfer GPS data"
description: |
  Convert, manipulate and transfer data from GPS programs or GPS
  recievers.  Open source and supported on macOS, Windows and Linux.

license: GPL-2.0
title: GPSBabel
source-code: https://github.com/GPSBabel/gpsbabel.git
website: https://www.gpsbabel.org

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  gpsbabel:
    extensions:
      - kde-neon-6
    plugs:
      - home
      - raw-usb
      - removable-media
      - serial-port
    command: usr/bin/gpsbabel
  gpsbabelfe:
    extensions:
      - kde-neon-6
    plugs:
      - home
      - removable-media
      - network
      - opengl
      - wayland
      - x11
    command-chain:
      - snap/command-chain/desktop-launch6
    command: usr/bin/gpsbabelfe

adopt-info: gpsbabel
parts:
  gpsbabel:
    # See 'snapcraft plugins'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DGPSBABEL_WITH_ZLIB=pkgconfig
      - -DGPSBABEL_WITH_SHAPELIB=pkgconfig
      - -DGPSBABEL_ENABLE_PCH=OFF
    cmake-generator: Ninja
    source: .
    override-pull: |
      craftctl default
      # add install command to CMakeLists.txt
      echo "install(TARGETS gpsbabel gpsbabelfe CONFIGURATIONS Release RUNTIME DESTINATION /usr/bin)" >> CMakeLists.txt
      # jam repo sha into GITHUB_SHA
      sed -i -e"/GB.SHA/i set(ENV{GITHUB_SHA} \"$(git log -1 --format=%h)\")" gbversion.cmake
      # set snap version
      # ensure version has at most 32 characters
      craftctl set version=$(git log -1 --format='LinuxInstaller-%ad-%h' --date=format:%Y%m%d)

    build-packages:
      - git
      - vim
      - g++
      - ninja-build
      - zlib1g-dev
      - libshp-dev
      - libusb-1.0-0-dev
      - pkg-config
      - libudev-dev
      - libvulkan-dev
      - libxkbcommon-dev
    stage-packages:
      - zlib1g
      - libshp2
      - libusb-1.0-0

  # https://snapcraft.io/docs/desktop-snap-size-reduction#heading--cleanup-part
  cleanup:
    after:
    - gpsbabel
    plugin: nil
    build-snaps:
    - core22
    - kf6-core22
    - kde-qt6-core22
    override-prime: |
      set -eux
      for snap in "core22" "kf6-core22" "kde-qt6-core22"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

