name: "build docker archive"
permissions: {}

on: 
  workflow_dispatch:

jobs:
  docker:
    name: docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: subdir1
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: tsteven4
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v6
      with:
        context: git
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and load
      uses: docker/build-push-action@v7
      with:
        context: subdir1
        load: true
