name: "travis"

on:
  push:
    branches: [ '**']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '27 4 * * 2'

jobs:
  basic:
    name: basic Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment
      env:
        LC_ALL: C.UTF-8

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v2

    - name: checkout
      run: |
        git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_REF:temporary-ci-branch
        git checkout $GITHUB_SHA

    - name: build_and_test
      run: |
        ./build_and_test

  qtio_gcc:
    name: qtio gcc Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment_qtio
      env:
        LC_ALL: C.UTF-8

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v2

    - name: checkout
      run: |
        git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_REF:temporary-ci-branch
        git checkout $GITHUB_SHA

    - name: build_and_test
      run: |
        . /opt/qtio.env
        ./build_and_test

  qtio_clang:
    name: qtio clang Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment_qtio
      env:
        QMAKESPEC: linux-clang
        LC_ALL: C.UTF-8

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v2

    - name: checkout
      run: |
        git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_REF:temporary-ci-branch
        git checkout $GITHUB_SHA

    - name: build_and_test
      run: |
        . /opt/qtio.env
        ./build_and_test

  advanced:
    name: advanced Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment_focal
      env:
        LC_ALL: C.UTF-8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build_extra_tests
      run: |
        ./tools/build_extra_tests

  fedora:
    name: fedora Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment_f32
      env:
        LC_ALL: C.UTF-8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build_and_test
      run: |
        ./build_and_test

  coverage:
    name: coverage Build
    runs-on: ubuntu-20.04
    steps:
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install gcovr lcov libusb-1.0-0-dev qt5-default

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: script
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        ./tools/travis_script_linux_coverage

  macos_release:
    name: macos release Build
    runs-on: macos-latest
    env:
      QT_VERSION: 5.12.10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Qt
      uses: actions/cache@v2
      with:
        path: ~/Cache
        key: ${{ runner.os }}-${{ env.QT_VERSION }}-${{ secrets.CACHE_VERSION }}

    - name: Qt install
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
      run: |
        ./tools/travis_install_osx ${QT_VERSION} installer

    - name: Script
      run: |
        source ${HOME}/Cache/qt-${QT_VERSION}.env
        sudo xcode-select --switch /Applications/Xcode_11.7.app
        ./tools/travis_script_osx
        echo GITHUB_REF: $GITHUB_REF

    - name: Deploy
      #if: ( github.ref == 'refs/heads/master' ) || ( github.base_ref == 'master' )
      # test
      if: ( github.ref == 'refs/heads/gitactions' ) || ( github.base_ref == 'master' )
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./tools/uploadtool/upload_github.sh gui/GPSBabel-*.dmg

  macos_edge:
    name: macos edge Build
    runs-on: macos-latest
    env:
      QT_VERSION: 5.15.2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Qt
      uses: actions/cache@v2
      with:
        path: ~/Cache
        key: ${{ runner.os }}-${{ env.QT_VERSION }}-${{ secrets.CACHE_VERSION }}

    - name: Qt install
      env:
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        ARTIFACTORY_BASE_URL: ${{ secrets.ARTIFACTORY_BASE_URL }}
      run: |
        ./tools/travis_install_osx ${QT_VERSION} artifactory

    - name: Script
      run: |
        source ${HOME}/Cache/qt-${QT_VERSION}.env
        sudo xcode-select --switch /Applications/Xcode_12.1.1.app
        ./tools/travis_script_osx


