name: "travis"

on:
  push:
    branches: [ master, gitactions]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '27 4 * * 2'

jobs:
  basic:
    name: basic Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment
      env:
        LC_ALL: C.UTF-8

    strategy:
      fail-fast: false

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v2

    - name: checkout
      run: |
        git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_REF:temporary-ci-branch
        git checkout $GITHUB_SHA

    - name: build_and_test
      run: |
        ./build_and_test

  qtio_gcc:
    name: qtio gcc Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment_qtio
      env:
        LC_ALL: C.UTF-8

    strategy:
      fail-fast: false

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v2

    - name: checkout
      run: |
        git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_REF:temporary-ci-branch
        git checkout $GITHUB_SHA

    - name: build_and_test
      run: |
        . /opt/qtio.env
        ./build_and_test

  qtio_clang:
    name: qtio clang Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment_qtio
      env:
        QMAKESPEC: linux-clang
        LC_ALL: C.UTF-8

    strategy:
      fail-fast: false

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v2

    - name: checkout
      run: |
        git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_REF:temporary-ci-branch
        git checkout $GITHUB_SHA

    - name: build_and_test
      run: |
        . /opt/qtio.env
        ./build_and_test

  advanced:
    name: advanced Build
    runs-on: ubuntu-latest
    container: 
      image: tsteven4/gpsbabel_build_environment_focal
      env:
        LC_ALL: C.UTF-8

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build_extra_tests
      run: |
        ls
        ./tools/build_extra_tests
