name: "windows"

on:
  push:
    branches: [ '**']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '27 4 * * 2'

jobs:

  windows:
    name: windows Build
    runs-on: windows-latest
    env:
      QT_VERSION: 5.12.10
      ARCH: x86_amd64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Qt
      uses: actions/cache@v2
      with:
        path: ~/Cache
        key: ${{ runner.os }}-${{ env.QT_VERSION }}-${{ env.ARCH }}-${{ secrets.CACHE_VERSION }}

    - name: Install Qt
      env:
        CI_BUILD_DIR: ${{ github.workspace }}
      shell: bash
      run: |
        ./tools/ci_install_windows.sh ${QT_VERSION} ${ARCH}

    - name: Build
      shell: cmd
      run: |
        SET PATH=%HOMEDRIVE%%HOMEPATH%\Cache\Qt\%QT_VERSION%\bin;%PATH%
        CALL "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
        powershell.exe -ExecutionPolicy Unrestricted -File tools\make_windows_release.ps1 -iscc "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" -buildinstaller true -flow nmake
