name: "windows"

on:
  push:
    branches: [ '**']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '27 4 * * 2'

jobs:

  windows:
    name: windows Build
    runs-on: windows-latest
    env:
      QT_VERSION: 5.12.10
      ARCH: x86_amd64
      COMPILER: msvc2017_64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Qt
      uses: actions/cache@v2
      with:
        path: ~/Cache
        key: ${{ runner.os }}-${{ env.QT_VERSION }}-${{ env.ARCH }}-${{ secrets.CACHE_VERSION }}-2

    - name: Install Qt
      env:
        CI_BUILD_DIR: ${{ github.workspace }}
      shell: bash
      run: |
        ./tools/ci_install_windows.sh ${QT_VERSION} ${ARCH}

    - name: Build
      shell: cmd
      run: |
        SET PATH=%HOMEDRIVE%%HOMEPATH%\Cache\Qt\%QT_VERSION%\%COMPILER%\bin;%PATH%
        CALL "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
        powershell.exe -ExecutionPolicy Unrestricted -File tools\make_windows_release.ps1 -iscc "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" -buildinstaller true -flow nmake

    - name: Test
      shell: bash
      run: |
        PATH="${HOME}/Cache/Qt/${QT_VERSION}/${COMPILER}/bin:${PATH}"
        PNAME=./release/GPSBabel.exe GBTEMP=./gbtemp ./testo 2>&1
        PNAME=./release/GPSBabel.exe GBTEMP=./gbtemp ./test_encoding_utf8 2>&1

    - name: Deploy
      shell: bash
      # This only handles continous releases now, for other events artifacts may be saved in
      # the 'Upload Artifacts' step.
      if: ( github.event_name == 'push' ) && ( github.ref == 'refs/heads/gitactions' )
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NAME: Continuous-${{ runner.os }}
      run: |
        VERSION_ID=$(date -u +%Y%m%dT%H%MZ --date=$(git show -s --format=%aI HEAD))-$(git rev-parse --short=7 HEAD)
        mv gui/release/GPSBabel-*-Setup.exe gui/release/GPSBabel-${VERSION_ID}-Setup.exe
        mv gui/release/GPSBabel-*-Manifest.txt gui/release/GPSBabel-${VERSION_ID}-Manifest.txt
        ./tools/uploadtool/upload_github.sh gui/release/GPSBabel-${VERSION_ID}-Setup.exe

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: Windows_Installer
        path: |
          ./gui/release/GPSBabel-*-Setup.exe
          ./gui/release/GPSBabel-*-Manifest.txt
        retention-days: 14
