name: "windows"

on:
  push:
    branches: [ '**']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '27 4 * * 2'

jobs:

  windows:
    name: windows Build
    runs-on: windows-latest
    env:
      QT_VERSION: 5.12.10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Qt
      uses: actions/cache@v2
      with:
        path: ~/Cache
        key: ${{ runner.os }}-${{ env.QT_VERSION }}-${{ secrets.CACHE_VERSION }}

    - name: Install Qt
      env:
        CI_BUILD_DIR: ${{ github.workspace }}
      shell: cmd
      run: |
        tools\ci_install_windows.bat

